### ISSUE TITLE
Merged Model Inference

### ISSUE THREAD

**Issue by Jankin66** [deepcs233/Visual-CoT#11]
Hi, I am highly interested in this work. However, I find it hard to directly infer on the **released merged weights**. Would it be possible to provide a simple inference script for the merged model? Thank you.
(e.g. https://huggingface.co/deepcs233/VisCoT-13b-224/tree/main)

**Comment by Jankin66** [comment]
`from llava.model import LlavaLlamaForCausalLM
from transformers import AutoTokenizer, AutoConfig
import torch
from func import eval_model
model_path = "models/VisCoT-13b-336"

kwargs = {"device_map": "auto",
        # "offload_folder": model_path,
        "cache_dir": r'./'
        }
kwargs['torch_dtype'] = torch.float16
lora_cfg_pretrained = AutoConfig.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
model = LlavaLlamaForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
vision_tower = model.get_vision_tower()
image_processor = vision_tower.image_processor

prompt = "what is in the image"
image_file = "https://llava-vl.github.io/static/images/view.jpg"

args = type('Args', (), {
    "model_path": model_path,
    "model_base": None,
    "query": prompt,
    "conv_mode": None,
    "image_file": image_file,
    "sep": ",",
    "temperature": 0,
    "top_p": None,
    "num_beams": 1,
    "max_new_tokens": 512
})()

eval_model(args,model,tokenizer,image_processor)
`

I use this code to generate, it seems work now.

**Comment by Jankin66** [comment]
```python
import argparse
import torch

from llava.constants import (
    IMAGE_TOKEN_INDEX,
    DEFAULT_IMAGE_TOKEN,
    DEFAULT_IM_START_TOKEN,
    DEFAULT_IM_END_TOKEN
)
IMAGE_PLACEHOLDER = "<image-placeholder>"

from llava.conversation import conv_templates, SeparatorStyle
from llava.model.builder import load_pretrained_model
from llava.utils import disable_torch_init
from llava.mm_utils import (
    process_images,
    tokenizer_image_token,
    get_model_name_from_path,
)

from PIL import Image

import requests
from PIL import Image
from io import BytesIO
import re


def image_parser(args):
    out = args.image_file.split(args.sep)
    return out


def load_image(image_file):
    if image_file.startswith("http") or image_file.startswith("https"):
        response = requests.get(image_file)
        image = Image.open(BytesIO(response.content)).convert("RGB")
    else:
        image = Image.open(image_file).convert("RGB")
    return image


def load_images(image_files):
    out = []
    for image_file in image_files:
        image = load_image(image_file)
        out.append(image)
    return out


def eval_model(args,model,tokenizer,image_processor):
    # Model
    disable_torch_init()

    qs = args.query
    image_token_se = DEFAULT_IM_START_TOKEN + DEFAULT_IMAGE_TOKEN + DEFAULT_IM_END_TOKEN
    if IMAGE_PLACEHOLDER in qs:
        if model.config.mm_use_im_start_end:
            qs = re.sub(IMAGE_PLACEHOLDER, image_token_se, qs)
        else:
            qs = re.sub(IMAGE_PLACEHOLDER, DEFAULT_IMAGE_TOKEN, qs)
    else:
        if model.config.mm_use_im_start_end:
            qs = image_token_se + "\n" + qs
        else:
            qs = DEFAULT_IMAGE_TOKEN + "\n" + qs

    conv_mode = "llava_v1"

    if args.conv_mode is not None and conv_mode != args.conv_mode:
        print(
            "[WARNING] the auto inferred conversation mode is {}, while `--conv-mode` is {}, using {}".format(
                conv_mode, args.conv_mode, args.conv_mode
            )
        )
    else:
        args.conv_mode = conv_mode

    conv = conv_templates[args.conv_mode].copy()
    conv.append_message(conv.roles[0], qs)
    conv.append_message(conv.roles[1], None)
    prompt = conv.get_prompt()

    image_files = image_parser(args)
    images = load_images(image_files)
    images_tensor = process_images(
        images,
        image_processor,
        model.config
    ).to(model.device, dtype=torch.float16)

    input_ids = (
        tokenizer_image_token(prompt, tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt")
        .unsqueeze(0)
        .cuda()
    )

    with torch.inference_mode():
        output_ids = model.generate(
            input_ids,
            images=images_tensor,
            do_sample=True if args.temperature > 0 else False,
            temperature=args.temperature,
            top_p=args.top_p,
            num_beams=args.num_beams,
            max_new_tokens=args.max_new_tokens,
            use_cache=True,
        )
    output_ids = torch.where(output_ids >= 0, output_ids, torch.tensor(0, device=output_ids.device))
    print(output_ids)
    outputs = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0].strip()
    print(outputs)

``` 
This is func changed from run_llava.py, hope it can help.

**Comment by xuanlongORZ** [comment]
Hey, thank you for your contribution. When I apply this code, it gives a single-round conversation after I provide the prompt and the image, like this:

> A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER:  
What number is associated with the bus line? ### Please think step by step and provide the bounding box coordinate of the region that can help you answer the question better. ### ASSISTANT: [0.771, 0.440, 0.811, 0.471]

Is it the same on your side? I thought it should be a multi-round conversation and provide an answer in the end with explainability.

**Comment by zhangquanchen** [comment]
已收到您的信件！

**Comment by zhangquanchen** [comment]
Hi, because the prompt directly asked to output is the boundingbox, which is the same as the first round of visualCOT dialogue. It's true, though, that this script doesn't support multi-round yet, so you can try append the first Q&A for the second dialogue.

**Comment by Valsure** [comment]
> This is func changed from run_llava.py, hope it can help.

Thank you for your solution, I applied the codes you provided and yet the problem remains:
```
Traceback (most recent call last):
  File "/mnt/general/liziheng/Visual-CoT/llava/eval/inference.py", line 1, in <module>
    from llava.model import LlavaLlamaForCausalLM
  File "/mnt/general/liziheng/Visual-CoT/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/mnt/general/liziheng/Visual-CoT/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "/mnt/general/liziheng/Visual-CoT/llava/model/language_model/llava_llama.py", line 139, in <module>
    AutoConfig.register("llava", LlavaConfig)
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1153, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 846, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.
```
to adress this I replaced 'llava' with 'llava_custom' , and another issue showed up:
```
Traceback (most recent call last):
  File "/mnt/general/liziheng/Visual-CoT/llava/eval/inference.py", line 14, in <module>
    model = LlavaLlamaForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3594, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/mnt/general/liziheng/Visual-CoT/llava/model/language_model/llava_llama.py", line 46, in __init__
    self.model = LlavaLlamaModel(config)
  File "/mnt/general/liziheng/Visual-CoT/llava/model/language_model/llava_llama.py", line 38, in __init__
    super(LlavaLlamaModel, self).__init__(config)
  File "/mnt/general/liziheng/Visual-CoT/llava/model/llava_arch.py", line 38, in __init__
    super(LlavaMetaModel, self).__init__(config)
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 958, in __init__
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 958, in <listcomp>
    [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 758, in __init__
    self.self_attn = LLAMA_ATTENTION_CLASSES[config._attn_implementation](config=config, layer_idx=layer_idx)
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 299, in __init__
    self.attention_dropout = config.attention_dropout
  File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/configuration_utils.py", line 265, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'LlavaConfig' object has no attribute 'attention_dropout'
```

**Comment by zhangquanchen** [comment]
> > This is func changed from run_llava.py, hope it can help.
> 
> Thank you for your solution, I applied the codes you provided and yet the problem remains:
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/general/liziheng/Visual-CoT/llava/eval/inference.py", line 1, in <module>
>     from llava.model import LlavaLlamaForCausalLM
>   File "/mnt/general/liziheng/Visual-CoT/llava/__init__.py", line 1, in <module>
>     from .model import LlavaLlamaForCausalLM
>   File "/mnt/general/liziheng/Visual-CoT/llava/model/__init__.py", line 1, in <module>
>     from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
>   File "/mnt/general/liziheng/Visual-CoT/llava/model/language_model/llava_llama.py", line 139, in <module>
>     AutoConfig.register("llava", LlavaConfig)
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1153, in register
>     CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 846, in register
>     raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
> ValueError: 'llava' is already used by a Transformers config, pick another name.
> ```
> 
> to adress this I replaced 'llava' with 'llava_custom' , and another issue showed up:
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/general/liziheng/Visual-CoT/llava/eval/inference.py", line 14, in <module>
>     model = LlavaLlamaForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3594, in from_pretrained
>     model = cls(config, *model_args, **model_kwargs)
>   File "/mnt/general/liziheng/Visual-CoT/llava/model/language_model/llava_llama.py", line 46, in __init__
>     self.model = LlavaLlamaModel(config)
>   File "/mnt/general/liziheng/Visual-CoT/llava/model/language_model/llava_llama.py", line 38, in __init__
>     super(LlavaLlamaModel, self).__init__(config)
>   File "/mnt/general/liziheng/Visual-CoT/llava/model/llava_arch.py", line 38, in __init__
>     super(LlavaMetaModel, self).__init__(config)
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 958, in __init__
>     [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 958, in <listcomp>
>     [LlamaDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 758, in __init__
>     self.self_attn = LLAMA_ATTENTION_CLASSES[config._attn_implementation](config=config, layer_idx=layer_idx)
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 299, in __init__
>     self.attention_dropout = config.attention_dropout
>   File "/mnt/general/liziheng/miniconda3/envs/cot/lib/python3.10/site-packages/transformers/configuration_utils.py", line 265, in __getattribute__
>     return super().__getattribute__(key)
> AttributeError: 'LlavaConfig' object has no attribute 'attention_dropout'
> ```

When facing "ValueError: 'llava' is already used by a Transformers config, pick another name."
 I use:
`pip install transformers==4.34.0`
And then it works, instead of replacing 'llava' with 'llava_custom'.

**Comment by Valsure** [comment]
> When facing "ValueError: 'llava' is already used by a Transformers config, pick another name." I use: `pip install transformers==4.34.0` And then it works, instead of replacing 'llava' with 'llava_custom'.

It works! much appreciated

**Comment by zhangquanchen** [comment]
> > When facing "ValueError: 'llava' is already used by a Transformers config, pick another name." I use: `pip install transformers==4.34.0` And then it works, instead of replacing 'llava' with 'llava_custom'.
> 
> It works! much appreciated

You are welcome.
