### ISSUE TITLE
Data with Detailed Reasoning Steps

### ISSUE THREAD

**Issue by zdou0830** [deepcs233/Visual-CoT#6]
Hello, thanks for your great work! The paper mentioned that there are ~98k instances annotated with detailed reasoning steps. I wonder if they are available? Thanks!

**Comment by zdou0830** [comment]
nvm. found it

**Comment by qumengxue** [comment]
> Hello, thanks for your great work! The paper mentioned that there are ~98k instances annotated with detailed reasoning steps. I wonder if they are available? Thanks!

Where did you find it?
